[package]
name = "cs2hl-cli"
edition.workspace = true
version.workspace = true
license.workspace = true

[[bin]]
name = "cs2hl"
path = "src/main.rs"

[dependencies]
cs2hl-core = { path = "../core" }
cs2hl-render = { path = "../render" }
anyhow.workspace = true
parser.workspace = true
serde_json.workspace = true
chrono = { version = "0.4", default-features = false, features = ["clock", "std"] }
