[package]
name = "veloxify"
edition.workspace = true
version.workspace = true
license.workspace = true

[[bin]]
name = "veloxify"
path = "src/main.rs"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
chrono = { version = "0.4", default-features = false, features = ["clock", "std"] }
tauri = { version = "2", features = ["tray-icon", "protocol-asset", "image-png"] }
tauri-plugin-notification = "2"
tauri-plugin-dialog = "2"
ureq = { version = "2", features = ["json"] }
cs2hl-core = { path = "../../crates/core" }
cs2hl-render = { path = "../../crates/render" }

[dependencies.windows]
version = "0.62"
features = ["Win32_Foundation", "Win32_System_Diagnostics_ToolHelp", "Win32_System_Registry"]
